### ISSUE TITLE
Errors: Exception propagated to the root monitor! AND Too many open files

### ISSUE THREAD

**Issue by bbbco** [twitter/diffy#52]
We're getting the following stack traces after running a script with many curl requests:

````
java -jar diffy-server.jar \
-candidate=<candidate host and port> \
-master.primary=<primary host and port> \
-master.secondary=<secondary host and port> \
-service.protocol=http \
-serviceName=<ServiceName> \
-proxy.port=:31900 \
-admin.port=:31159 \
-http.port=:31149 \
-rootUrl='localhost:31149'
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
I 1108 15:42:23.086 THREAD1: HttpMuxer[/admin/metrics.json] = com.twitter.finagle.stats.MetricsExporter(<function1>)
I 1108 15:42:23.108 THREAD1: HttpMuxer[/admin/per_host_metrics.json] = com.twitter.finagle.stats.HostMetricsExporter(<function1>)
I 1108 15:42:23.143 THREAD1: /admin => com.twitter.server.handler.SummaryHandler
I 1108 15:42:23.143 THREAD1: /admin/server_info => com.twitter.finagle.Filter$$anon$2
I 1108 15:42:23.143 THREAD1: /admin/contention => com.twitter.finagle.Filter$$anon$2
I 1108 15:42:23.143 THREAD1: /admin/threads => com.twitter.server.handler.ThreadsHandler
I 1108 15:42:23.143 THREAD1: /admin/threads.json => com.twitter.server.handler.ThreadsHandler
I 1108 15:42:23.143 THREAD1: /admin/announcer => com.twitter.finagle.Filter$$anon$2
I 1108 15:42:23.143 THREAD1: /admin/dtab => com.twitter.finagle.Filter$$anon$2
I 1108 15:42:23.144 THREAD1: /admin/pprof/heap => com.twitter.server.handler.HeapResourceHandler
I 1108 15:42:23.144 THREAD1: /admin/pprof/profile => com.twitter.server.handler.ProfileResourceHandler
I 1108 15:42:23.144 THREAD1: /admin/pprof/contention => com.twitter.server.handler.ProfileResourceHandler
I 1108 15:42:23.144 THREAD1: /admin/ping => com.twitter.server.handler.ReplyHandler
I 1108 15:42:23.144 THREAD1: /admin/shutdown => com.twitter.server.handler.ShutdownHandler
I 1108 15:42:23.144 THREAD1: /admin/tracing => com.twitter.server.handler.TracingHandler
I 1108 15:42:23.144 THREAD1: /admin/events => com.twitter.server.handler.EventsHandler
I 1108 15:42:23.144 THREAD1: /admin/logging => com.twitter.server.handler.LoggingHandler
I 1108 15:42:23.145 THREAD1: /admin/metrics => com.twitter.server.handler.MetricQueryHandler
I 1108 15:42:23.145 THREAD1: /admin/clients/ => com.twitter.server.handler.ClientRegistryHandler
I 1108 15:42:23.145 THREAD1: /admin/servers/ => com.twitter.server.handler.ServerRegistryHandler
I 1108 15:42:23.145 THREAD1: /admin/files/ => com.twitter.server.handler.ResourceHandler
I 1108 15:42:23.145 THREAD1: /admin/registry.json => com.twitter.server.handler.RegistryHandler
I 1108 15:42:23.146 THREAD1: Serving admin http on 0.0.0.0/0.0.0.0:31159
I 1108 15:42:23.159 THREAD1: Finagle version 6.28.0 (rev=de123b8f9d074c4e345ebd67e1a0e870bb921544) built at 20150827-162434
I 1108 15:42:23.622 THREAD1: networkaddress.cache.ttl is not set, DNS cache refresh turned off
I 1108 15:42:23.804 THREAD1: Tracer: com.twitter.finagle.zipkin.thrift.SamplingTracer
I 1108 15:42:23.950 THREAD1: zipkin-tracer resolved to Addr.Bound, current size=1
I 1108 15:42:23.951 THREAD1: candidate resolved to Addr.Bound, current size=1
I 1108 15:42:23.951 THREAD1: primary resolved to Addr.Bound, current size=1
I 1108 15:42:23.951 THREAD1: secondary resolved to Addr.Bound, current size=1
I 1108 15:42:23.997 THREAD1: Scheduling com.twitter.diffy.workflow.FunctionalReport at 2016-11-08 15:42:23 +0000
E 1108 15:54:36.281 THREAD15: Exception propagated to the root monitor!
scala.MatchError: ClientRecvError(scala.MatchError: WireSend (of class com.twitter.finagle.tracing.Annotation$WireSend$)) (of class com.twitter.finagle.tracing.Annotation$ClientRecvError)
	at com.twitter.finagle.zipkin.thrift.RawZipkinTracer.record(RawZipkinTracer.scala:210)
	at com.twitter.finagle.zipkin.thrift.SamplingTracer.record(ZipkinTracer.scala:199)
	at com.twitter.finagle.tracing.DefaultTracer$.record(Tracer.scala:147)
	at com.twitter.finagle.tracing.Trace$$anonfun$uncheckedRecord$1.apply(Trace.scala:266)
	at com.twitter.finagle.tracing.Trace$$anonfun$uncheckedRecord$1.apply(Trace.scala:266)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.twitter.finagle.tracing.Trace$.uncheckedRecord(Trace.scala:266)
	at com.twitter.finagle.tracing.Trace$.record(Trace.scala:312)
	at com.twitter.finagle.tracing.AnnotatingTracingFilter$$anonfun$apply$4.apply(TraceInitializerFilter.scala:154)
	at com.twitter.finagle.tracing.AnnotatingTracingFilter$$anonfun$apply$4.apply(TraceInitializerFilter.scala:150)
	at com.twitter.util.Promise$Monitored.apply(Promise.scala:73)
	at com.twitter.util.Promise$Monitored.apply(Promise.scala:64)
	at com.twitter.util.Promise$$anon$2.run(Promise.scala:358)
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:193)
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:140)
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:222)
	at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:84)
	at com.twitter.util.Promise.runq(Promise.scala:342)
	at com.twitter.util.Promise.updateIfEmpty(Promise.scala:713)
	at com.twitter.util.Promise.update(Promise.scala:686)
	at com.twitter.util.Promise.setValue(Promise.scala:662)
	at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:88)
	at com.twitter.finagle.netty3.transport.ChannelTransport.handleUpstream(ChannelTransport.scala:51)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
	at com.twitter.finagle.netty3.channel.ChannelRequestStatsHandler.messageReceived(ChannelRequestStatsHandler.scala:35)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.messageReceived(SimpleChannelUpstreamHandler.java:124)
	at com.twitter.finagle.http.codec.RespondToExpectContinue.messageReceived(RespondToExpectContinue.scala:29)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpContentEncoder.messageReceived(HttpContentEncoder.java:82)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.handler.codec.http.HttpServerCodec.handleUpstream(HttpServerCodec.java:56)
	at com.twitter.finagle.http.SafeHttpServerCodec.handleUpstream(Codec.scala:41)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
	at com.twitter.finagle.netty3.channel.ChannelStatsHandler.messageReceived(ChannelStatsHandler.scala:80)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
.......
W 1108 16:10:17.292 THREAD22 org.jboss.netty.channel.socket.nio.AbstractNioSelector: Failed to accept a connection.
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

W 1108 16:10:18.293 THREAD22 org.jboss.netty.channel.socket.nio.AbstractNioSelector: Failed to accept a connection.
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

W 1108 16:10:19.293 THREAD22 org.jboss.netty.channel.socket.nio.AbstractNioSelector: Failed to accept a connection.
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
````

Maybe we are straining the process too hard? Do you have any input on the expected scalability and performance that we should expect when running multiple requests?

**Comment by anandhravindran** [comment]
Hi @bbbco , Were you able to resolve this issue ? I am also facing a similar issue with record of zipkin. Please find the stack trace below

scala.MatchError: WireSend (of class com.twitter.finagle.tracing.Annotation$WireSend$)
        at com.twitter.finagle.zipkin.thrift.RawZipkinTracer.record(RawZipkinTracer.scala:210)
        at com.twitter.finagle.zipkin.thrift.SamplingTracer.record(ZipkinTracer.scala:199)
        at com.twitter.finagle.tracing.DefaultTracer$.record(Tracer.scala:147)
        at com.twitter.finagle.tracing.Trace$$anonfun$uncheckedRecord$1.apply(Trace.scala:266)
        at com.twitter.finagle.tracing.Trace$$anonfun$uncheckedRecord$1.apply(Trace.scala:266)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at com.twitter.finagle.tracing.Trace$.uncheckedRecord(Trace.scala:266)
        at com.twitter.finagle.tracing.Trace$.record(Trace.scala:312)
        at com.twitter.finagle.tracing.AnnotatingTracingFilter.apply(TraceInitializerFilter.scala:149)
        at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:85)
        at com.twitter.finagle.ServiceProxy.apply(Service.scala:115)
        at com.twitter.finagle.ServiceProxy.apply(Service.scala:115)
        at com.twitter.finagle.Service$$anon$2.apply(Service.scala:15)
        at com.twitter.finagle.service.TimeoutFilter$$anonfun$apply$2.apply(TimeoutFilter.scala:111)
        at com.twitter.finagle.service.TimeoutFilter$$anonfun$apply$2.apply(TimeoutFilter.scala:110)
        at com.twitter.util.Local.let(Local.scala:131)
        at com.twitter.finagle.context.Context$class.let(Context.scala:176)
        at com.twitter.finagle.context.MarshalledContext.let(Context.scala:209)
        at com.twitter.finagle.service.TimeoutFilter.apply(TimeoutFilter.scala:110)
        at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:85)
        at com.twitter.finagle.service.FailureAccrualFactory$$anonfun$apply$2$$anon$2.apply(FailureAccrualFactory.scala:206)
        at com.twitter.finagle.Service$$anon$2.apply(Service.scala:15)
        at com.twitter.finagle.service.StatsFilter.apply(StatsFilter.scala:126)
        at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:85)
        at com.twitter.finagle.Service$$anon$2.apply(Service.scala:15)
        at com.twitter.finagle.filter.DtabStatsFilter.apply(DtabStatsFilter.scala:37)
        at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:85)
        at com.twitter.finagle.Service$$anon$2.apply(Service.scala:15)
        at com.twitter.finagle.tracing.ClientDestTracingFilter.apply(DestinationTracing.scala:64)
        at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:85)

@puneetkhanduri  Is there a way to disable sending traces to zipkin? Is zipkin needed as a dependency for diffy?

**Comment by AchinthyaBhat** [comment]
@bbbco did you find a fix for it? I am facing a very similar issues.
Stacktrace:

E 0730 16:32:03.078 THREAD28: Exception propagated to the root monitor!
scala.MatchError: ClientRecvError(scala.MatchError: WireSend (of class com.twitter.finagle.tracing.Annotation$WireSend$)) (of class com.twitter.finagle.tracing.Annotation$ClientRecvError)
	at com.twitter.finagle.zipkin.thrift.RawZipkinTracer.record(RawZipkinTracer.scala:210)
	at com.twitter.finagle.zipkin.thrift.SamplingTracer.record(ZipkinTracer.scala:199)
	at com.twitter.finagle.tracing.DefaultTracer$.record(Tracer.scala:147)
	at com.twitter.finagle.tracing.Trace$$anonfun$uncheckedRecord$1.apply(Trace.scala:266)
	at com.twitter.finagle.tracing.Trace$$anonfun$uncheckedRecord$1.apply(Trace.scala:266)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.twitter.finagle.tracing.Trace$.uncheckedRecord(Trace.scala:266)
	at com.twitter.finagle.tracing.Trace$.record(Trace.scala:312)
	at com.twitter.finagle.tracing.AnnotatingTracingFilter$$anonfun$apply$4.apply(TraceInitializerFilter.scala:154)
	at com.twitter.finagle.tracing.AnnotatingTracingFilter$$anonfun$apply$4.apply(TraceInitializerFilter.scala:150)
	at com.twitter.util.Promise$Monitored.apply(Promise.scala:73)
	at com.twitter.util.Promise$Monitored.apply(Promise.scala:64)
	at com.twitter.util.Promise$$anon$2.run(Promise.scala:358)
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:193)
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:140)
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:222)
	at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:84)
	at com.twitter.util.Promise.runq(Promise.scala:342)
	at com.twitter.util.Promise.updateIfEmpty(Promise.scala:713)
	at com.twitter.util.Promise.update(Promise.scala:686)
	at com.twitter.util.Promise.setValue(Promise.scala:662)
	at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:88)
	at com.twitter.finagle.netty3.transport.ChannelTransport.handleUpstream(ChannelTransport.scala:51)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
	at com.twitter.finagle.netty3.channel.ChannelRequestStatsHandler.messageReceived(ChannelRequestStatsHandler.scala:35)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.messageReceived(SimpleChannelUpstreamHandler.java:124)
	at com.twitter.finagle.http.codec.RespondToExpectContinue.messageReceived(RespondToExpectContinue.scala:29)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpContentEncoder.messageReceived(HttpContentEncoder.java:82)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.handler.codec.http.HttpServerCodec.handleUpstream(HttpServerCodec.java:56)
	at com.twitter.finagle.http.SafeHttpServerCodec.handleUpstream(Codec.scala:41)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
	at com.twitter.finagle.netty3.channel.ChannelStatsHandler.messageReceived(ChannelStatsHandler.scala:80)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
