### ISSUE TITLE
Feature request: supporting text/plain

### ISSUE THREAD

**Issue by daleiawei** [twitter/diffy#82]
When I use diffy to test, I found when response includes content type 'text/plain', the diffy would not handle the response and got following error log:

```
D 0108 07:01:08.812 THREAD39: success networking
D 0108 07:01:08.813 THREAD39: Content type: text/plain; charset=utf-8 is not supported
D 0108 07:01:08.813 THREAD39: Content type: text/plain; charset=utf-8 is not supported
D 0108 07:01:08.813 THREAD39: Content type: text/plain; charset=utf-8 is not supported
D 0108 07:01:08.813 THREAD39: error lifting
java.lang.Exception: Content type: text/plain; charset=utf-8 is not supported
  at com.twitter.diffy.lifter.HttpLifter$.contentTypeNotSupportedException(HttpLifter.scala:15)
  at com.twitter.diffy.lifter.HttpLifter$.contentTypeNotSupportedExceptionFuture(HttpLifter.scala:16)
  at com.twitter.diffy.lifter.HttpLifter$$anonfun$liftResponse$1.apply(HttpLifter.scala:113)
  at com.twitter.diffy.lifter.HttpLifter$$anonfun$liftResponse$1.apply(HttpLifter.scala:50)
  at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:890)
  at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:889)
```

I also saw there's feature requested to support 'text/xml' before, please also considering to add the type of 'text/plain', thanks a lot for providing the excellent tool !

**Comment by puneetkhanduri** [comment]
Please use https://github.com/opendiffy/diffy. This issue has been resolved there.

**Comment by puneetkhanduri** [comment]
The opendiffy readme includes a docker section. Are you having trouble using the docker image?
