### ISSUE TITLE
readme error:  using diffy with docker

### ISSUE THREAD

**Issue by ZhMi** [twitter/diffy#95]
Hello, 
There seem to be two problems with the README file.
I use the lastest docker which is updated three days ago.

-------------------------
Problem One:
If I use the following command, there will be an error.

```bash
docker run -ti \
  -p 8880:8880 -p 8881:8881 -p 8888:8888 \
  diffy/diffy \
    -candidate=localhost:9992 \
    -master.primary=localhost:9990 \
    -master.secondary=localhost:9991 \
    -service.protocol=http \
    -serviceName="Test-Service" \
    -proxy.port=:8880 \
    -admin.port=:8881 \
    -http.port=:8888 \
    -rootUrl=localhost:8888
```

```bash
(1) Error in custom provider, java.lang.IllegalArgumentException: flag 'summary.email' not found
  at ai.diffy.DiffyServiceModule$.settings(DiffyServiceModule.scala:82) (via modules: com.google.inject.util.Modules$OverrideModule -> ai.diffy.DiffyServiceModule$)
  at ai.diffy.DiffyServiceModule$.settings(DiffyServiceModule.scala:82) (via modules: com.google.inject.util.Modules$OverrideModule -> ai.diffy.DiffyServiceModule$)
  while locating ai.diffy.proxy.Settings
Caused by: java.lang.IllegalArgumentException: flag 'summary.email' not found`
```
The command needs to add param 'summary.email'. 
 
```bash
docker run -ti \
  -p 8880:8880 -p 8881:8881 -p 8888:8888 \
  diffy/diffy \
    -candidate=localhost:9992 \
    -master.primary=localhost:9990 \
    -master.secondary=localhost:9991 \
    -service.protocol=http \
    -serviceName="Test-Service" \
    -proxy.port=:8880 \
    -admin.port=:8881 \
    -http.port=:8888 \
    -rootUrl=localhost:8888
    -summary.email=""
```

This command will work fine. 

----------------------------

Problem Two:
docker build -t diffy .  
This command executed failed.
```bash
Sending build context to Docker daemon  6.061MB
Step 1/8 : FROM hseeberger/scala-sbt
manifest for hseeberger/scala-sbt:latest not found
```
The Dockerfile use hseeberger/scala-sbt  mirror.  
https://hub.docker.com/r/hseeberger/scala-sbt/tags?page=2 
But there is no version definition in the dockerFile. So the command will use lasted vision will be used.  Mirror  hseeberger/scala-sbt 
has no tag version called latest.

**Comment by puneetkhanduri** [comment]
Sorry for the trouble. Updated the readme.
